package billapp.view;

import billapp.logic.User;
import billapp.persistence.DB;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 * Frame Forgot class
 * @author jf
 */
public class FraForgot extends javax.swing.JFrame {
    private DB dataFile;            /** Database file */

    /**
     * Creates new form FraForgot
     */
    public FraForgot() {
        initComponents();
    }

    /**
     * Creates new form FraForgot
     * @param dataFile Database file
     */
    public FraForgot(DB dataFile) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.dataFile = dataFile;
    }

    /**
     * Get Data file
     * @return Data file
     */
    public DB getDataFile() {
        return this.dataFile;
    }

    /**
     * Set Data file
     * @param dataFile Data file
     */
    public void setDataFile(DB dataFile) {
        this.dataFile = dataFile;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labMessage = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        butSend = new javax.swing.JButton();

        setTitle("Forgot your password?");

        labMessage.setText("Please enter your e-mail address registered");

        butSend.setText("Send");
        butSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(butSend)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(butSend)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Send button
     * @param evt Event
     */
    private void butSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSendActionPerformed
        if (this.validateEmail()) {
            if (this.searchEmail()) {
                String password = this.getRandomPassword(10);
                this.sendEmail(password);
                this.updatePassword(password);
                JOptionPane.showMessageDialog(this, 
                        "Email was successfully sent!", 
                        "Email was sent", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, 
                        "Sorry, this email was not registered!", 
                        "Email not registered", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, 
                    "Sorry, this email is wrong!", 
                    "Wrong email", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butSendActionPerformed

    /**
     * Validate email address
     * @return True = email address is correct!
     */
    private boolean validateEmail() {
        return (!txtEmail.getText().equals("")
                && txtEmail.getText().contains("@") 
                && txtEmail.getText().contains("."));
    }

    /**
     * Search registered email
     */
    private boolean searchEmail() {
        boolean find = false;
        try {
            if (this.getDataFile().getResultSet() != null) {
                this.getDataFile().getResultSet().beforeFirst();
                while (this.getDataFile().getResultSet().next()) {
                    if (this.getDataFile().getResultSet().getString("email")
                            .equals(txtEmail.getText())) {
                        find = true;
                        break;
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FraLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return find;
    }

    /**
     * Send a email
     */
    private void sendEmail(String password) {
        try {
            String to = txtEmail.getText();
            String from = "juanfmendozam@yahoo.com";
            String host = "smtp.mail.yahoo.com";
            String pass = "*********";
            int port = 587;

            Properties properties = System.getProperties();
            properties.put("mail.transport.protocol", "smtp");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host", host);
            properties.put("mail.smtp.user", from);
            properties.put("mail.smtp.password", pass);
            properties.put("mail.smtp.port", "" + port);
            properties.put("mail.smtp.auth", "true");

            Session session = Session.getDefaultInstance(properties);
            MimeMessage message = new MimeMessage(session);

            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            message.setSubject("BillApp new password!");
            message.setText("This is a new password for BillApp:"
                    + "\nUsername: " + this.getDataFile().getResultSet().getString("username")
                    + "\nPassword: " + password);

            Transport transport = session.getTransport("smtp");
            transport.connect(host, port, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
        } catch (MessagingException | SQLException ex) {
            Logger.getLogger(FraForgot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Generate a random password
     * @param length Password length
     * @return New password
     */
    private String getRandomPassword(int length) {
        String randomString = "";
        long mils = new java.util.GregorianCalendar().getTimeInMillis();
        Random r = new Random(mils);
        int i = 0;
        while ( i < length){
            char c = (char)r.nextInt(255);
            if ( (c >= '0' && c <='9') || (c >='A' && c <='Z') ) {
                randomString += c;
                i ++;
            }
        }
        return randomString;
    }

    /**
     * Update new password
     * @param password New password
     */
    private void updatePassword(String password) {
        try {
            String username = this.getDataFile().getResultSet().getString("username");
            User user = new User();
            user.setPassword(password);
            String query = "UPDATE User SET "
                + "password = '" + user.getPassword() + "' "
                + "WHERE username = '" + username + "'";
            if (this.getDataFile().execute(query)) {
            }
        } catch (SQLException ex) {
            Logger.getLogger(FraForgot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FraForgot().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSend;
    private javax.swing.JLabel labMessage;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
