package billapp.view;

import billapp.persistence.DB;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * FraLogin class
 * @author jf
 */
public class FraLogin extends javax.swing.JFrame {
    private DB dataFile;            /** Database file */

    /**
     * Creates new form FraLogin
     */
    public FraLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.dataFile = new DB();
        this.dataFile.connectMSAccess("/home/jf/NetBeansProjects/BillApp/Git/BillApp/BillApp/src/billapp/persistence/BillDB.accdb");
        this.selectUser();
    }

    /**
     * Get Data file
     * @return Data file
     */
    public DB getDataFile() {
        return this.dataFile;
    }

    /**
     * Set Data file
     * @param dataFile Data file
     */
    public void setDataFile(DB dataFile) {
        this.dataFile = dataFile;
    }

    /**
     * Select employees from DB
     */
    private void selectUser() {
        String query = "SELECT * FROM User";
        if (this.getDataFile().execute(query)) {
            try {
                this.getDataFile().getResultSet().next();
            } catch (SQLException ex) {
                Logger.getLogger(FraUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labUsername = new javax.swing.JLabel();
        labPassword = new javax.swing.JLabel();
        butLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        pasPassword = new javax.swing.JPasswordField();
        butForgot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill App Login");
        setName("fraLogin"); // NOI18N

        labUsername.setText("Username");

        labPassword.setText("Password");

        butLogin.setText("Login");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        butForgot.setText("Forgot your password?");
        butForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butForgotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labUsername)
                            .addComponent(labPassword))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pasPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtUsername))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butForgot)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butLogin)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labPassword))
                .addGap(29, 29, 29)
                .addComponent(butLogin)
                .addGap(27, 27, 27)
                .addComponent(butForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Login button
     * @param evt Event
     */
    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        if (this.isPassword(txtUsername.getText(), new String(pasPassword.getPassword()))) {
            try {
                BillAppMDI mdiForm = new BillAppMDI(this.getDataFile(), 
                        this.getDataFile().getResultSet().getInt("userLevel"));
                mdiForm.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(FraLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, 
                    "Sorry, Username and password do not match!", "Login",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butLoginActionPerformed

    /**
     * Forgot your password?
     * @param evt Event
     */
    private void butForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butForgotActionPerformed
        FraForgot forgotForm = new FraForgot(this.getDataFile());
        forgotForm.setVisible(true);
    }//GEN-LAST:event_butForgotActionPerformed

    /**
     * Compare username/password entered by user with username/password from DB
     * @param username Username
     * @param password Password
     * @return True is correct
     */
    private boolean isPassword(String username, String password) {
        boolean correct = false;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(password.getBytes(), 0, password.length());
            password = new BigInteger(1, md.digest()).toString(16);

            if (this.getDataFile().getResultSet() != null) {
                this.getDataFile().getResultSet().beforeFirst();
                while (this.getDataFile().getResultSet().next()) {
                    if (this.getDataFile().getResultSet().getString("username")
                            .equals(username)) {
                        if (this.getDataFile().getResultSet()
                                .getString("password").equals(password)) {
                            correct = true;
                        }
                        break;
                    }
                }
            }
        } catch (NoSuchAlgorithmException | SQLException ex) {
            Logger.getLogger(FraLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return correct;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FraLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butForgot;
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel labPassword;
    private javax.swing.JLabel labUsername;
    private javax.swing.JPasswordField pasPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
